### PR TITLE
fix readthedocs build definition

### PR DESCRIPTION
**Pull request by chipitsine**
for the reference: https://github.com/readthedocs/readthedocs.org/issues/11173

### CODE REVIEW

**Comment by chipitsine** [comment]
Ping

**Comment by chipitsine** [comment]
ping

**Comment by chipitsine** [comment]
@wal-g/committers  please ?

**Review by x4m — APPROVED** [review]

**Comment by x4m** [comment]
Sorry, when pings are not personal it’s so easy to miss them.

**Pull request merged**
