### PR TITLE
Add PgDataSetting true to config.go for fix #549

### LINKED ISSUE #549: PGDATA is unknown if use .walg.json
```
cat $HOME/.walg.json
{
  "WALE_S3_PREFIX": "s3://pg-backups",
  "AWS_ACCESS_KEY_ID": "minio",
  "AWS_ENDPOINT": "http://172.26.9.241:9000",
  "AWS_S3_FORCE_PATH_STYLE": "true",
  "AWS_SECRET_ACCESS_KEY": "miniosecret",
  "PGDATA": "/var/lib/pgsql/9.6/data/",
  "PGHOST": "/var/run/postgresql/.s.PGSQL.5432",
  "WALG_UPLOAD_CONCURRENCY": "2",
  "WALG_DOWNLOAD_CONCURRENCY": "2",
  "WALG_UPLOAD_DISK_CONCURRENCY": "2",
  "WALG_DELTA_MAX_STEPS": "7",
  "WALG_COMPRESSION_METHOD": "brotli"
}
```

Get error:
```
usr/local/bin/wal-g backup-list
WARNING: 2020/02/02 12:33:32.793829 PGDATA is unknown
WARNING: 2020/02/02 12:33:32.793865 We found that some variables in your config file detected as 'Unknown'. 
  If this is not right, please create issue https://github.com/wal-g/wal-g/issues/new
name                          last_modified        wal_segment_backup_start
```

### PR DESCRIPTION
**Pull request by patsevanton**
Fix https://github.com/wal-g/wal-g/issues/549

### CODE REVIEW

**Comment by patsevanton** [comment]
image

**Comment by patsevanton** [comment]
image

**Comment by patsevanton** [comment]
image

**Comment by patsevanton** [comment]
image

**Comment by patsevanton** [comment]
image

**Comment by patsevanton** [comment]
image

**Comment by x4m** [comment]
I think in case of backup-push we should validate the value of this setting against command argument.
So that if you have pgdata /var/lib/postgres/11/data in config and run wal-g backup-push /var/lib/postgres/12/data... I think you should get warning at least...

**Comment by patsevanton** [comment]
If we create full backup, then don`t change pgdata. I think.

Scenario:
Run  backup-push with pgdata /var/lib/postgres/11/data
Remove PostgreSQL 11
Install PostgreSQL 12
Change .walg.json
Run backup-fetch

**Comment by patsevanton** [comment]
@x4m add check PGDATA in config and cli and add get warning
https://github.com/wal-g/wal-g/pull/574/commits/54f18626ef50e6a9d442408c7d4a35d42d847969

**Comment by oangit** [comment]
Could you please tell me, when will the release include this pull request?

**Pull request merged**
