### PR TITLE
Optional brotli rebase

### PR DESCRIPTION
**Pull request by serprex**
Rebased #634  to master after cleaning up the original PR (merging typo fix, reverting unnecessary changes to delete_handler.go/go.mod/go.sum)

### CODE REVIEW

**Comment by serprex** [comment]
@usernamedt I'm not having any luck figuring out where gp_test sets WALG_COMPRESSION_METHOD=brotli, are you able to take a look?

**Comment by usernamedt** [comment]
> @usernamedt I'm not having any luck figuring out where gp_test sets WALG_COMPRESSION_METHOD=brotli, are you able to take a look?

Hi! Sorry for the late reply, am I correct that it is no longer relevant?

**Comment by serprex** [comment]
@usernamedt yesterday I tried rebasing this PR again, seems it wasn't so clean. Your understanding is correct

**Comment by serprex** [comment]
Closing as at this point I'd probably want to start from the original PR anyways since this ended up being far from 1 failing test with interim changes

**Pull request closed without merging**
