### PR TITLE
WALG_DELTA_ORIGIN=LATEST_FULL fix

### PR DESCRIPTION
**Pull request by kruftik**
Fixes wal-g#406

### CODE REVIEW

**Comment by phumpal** [comment]
The parent issue persists in v0.2.15. It would be nice to see this reviewed+merged.

**Comment by x4m** [comment]
@kruftik @phumpal Sorry, I've totally forgot about this PR. Let's get it merged.
But there are few problems:
1. It will still error out if we don't have any backups and try to run delta from full backup. I think we should just make a full backup in this case.
2. We do not need to fetch list of backups again. We already have a name of previous backup, it must be there in a storage, unless user messed with the storage.

I propose checking for that previousBackupSentinelDto == nil and fallback to full backup in this case.

**Comment by phumpal** [comment]
Awesome, thanks for the quick response @x4m 

> previousBackupSentinelDto == nil and fallback to full backup in this case.

:+1: for usability; this seems like a good approach.

>  must be there in a storage, unless user messed with the storage

Gentle ping @kruftik otherwise I'm happy try in a new PR.

**Comment by kruftik** [comment]
It was not an easy task to catch up with the issue itself and PR after almost an year has passed :) 


@x4m,

> It will still error out if we don't have any backups and try to run delta from full backup. I think we should just make a full backup in this case.

I can't figure out, how such an event can happen, given the code:

```go
		previousBackupName, err = getLatestBackupName(folder)
		if err != nil {
			if _, ok := err.(NoBackupsFoundError); ok {
				tracelog.InfoLogger.Println("Couldn't find previous backup. Doing full backup.")
			} else {
				tracelog.ErrorLogger.FatalError(err)
			}
```

> I propose checking for that previousBackupSentinelDto == nil and fallback to full backup in this case.

I believe you meant checking for nil of previousBackupSentinelDto.IncrementFullName since previousBackupSentinelDto can't be nil at all

> We do not need to fetch list of backups again. We already have a name of previous backup, it must be there in a storage, unless user messed with the storage.

reworked the PR a bit, now previousBackupName used as the delta source if previous nil-check was true

**Comment by x4m** [comment]
Looks good to me. @kruftik , thanks!

**Pull request merged**
