### PR TITLE
Fix problem with dot directory wal-g/issues/258

### PR DESCRIPTION
**Pull request by Denchick**

### CODE REVIEW

**Comment by Denchick** [comment]
I'll resend.

**Comment by Denchick** [comment]
Its a bit strange that in this PR there are commits 74bd9ac and 5394a25. They was merged in https://github.com/wal-g/wal-g/pull/467.

So, i just want send fix to wal-g/issues/258.
It could be cool to write tests for

**Comment by g0djan** [comment]
Actually we can test it completely in integration tests, but it will be too long or not clear, so just make a test that you described.

**Comment by osterboss86** [comment]
Fr

**Pull request closed without merging**
