### PR TITLE
internal/backup.go: Fixed restore from delta backup.

### PR DESCRIPTION
**Pull request by tatodorov**
This resolves issue #499.

Below, you will find an output from restoring from delta backup which completes successfully.

```
postgres@66f5e913e6cd:~/go/src/wal-g# ./main/pg/wal-g backup-list
name                                                     last_modified        wal_segment_backup_start
base_000000010000000000000056                            2019-12-11T09:27:48Z 000000010000000000000056
base_000000010000000000000058_D_000000010000000000000056 2019-12-11T09:29:32Z 000000010000000000000058
base_00000001000000000000005A_D_000000010000000000000058 2019-12-11T09:29:56Z 00000001000000000000005A
base_00000001000000000000005C_D_00000001000000000000005A 2019-12-11T09:30:20Z 00000001000000000000005C
base_00000001000000000000005E_D_00000001000000000000005C 2019-12-11T09:30:32Z 00000001000000000000005E
base_00000001000000000000005F_D_00000001000000000000005E 2019-12-11T09:30:42Z 00000001000000000000005F
base_000000010000000000000061_D_00000001000000000000005F 2019-12-11T09:30:53Z 000000010000000000000061
base_000000010000000000000062                            2019-12-11T09:31:06Z 000000010000000000000062
base_000000010000000000000064_D_000000010000000000000062 2019-12-11T09:31:20Z 000000010000000000000064
base_000000010000000000000065_D_000000010000000000000064 2019-12-11T09:31:29Z 000000010000000000000065
base_000000010000000000000067_D_000000010000000000000065 2019-12-11T09:31:35Z 000000010000000000000067
base_000000010000000000000068_D_000000010000000000000067 2019-12-11T09:31:43Z 000000010000000000000068
base_000000010000000000000069_D_000000010000000000000068 2019-12-11T09:31:49Z 000000010000000000000069
base_00000001000000000000006B_D_000000010000000000000069 2019-12-11T09:31:58Z 00000001000000000000006B
```

```
postgres@66f5e913e6cd:~/go/src/wal-g# ./main/pg/wal-g backup-fetch /pg_data base_00000001000000000000006B_D_000000010000000000000069
INFO: 2019/12/18 11:08:20.304833 Delta from base_000000010000000000000069_D_000000010000000000000068 at LSN 69000028
INFO: 2019/12/18 11:08:21.880173 Delta from base_000000010000000000000068_D_000000010000000000000067 at LSN 68000028
INFO: 2019/12/18 11:08:22.906677 Delta from base_000000010000000000000067_D_000000010000000000000065 at LSN 67000028
INFO: 2019/12/18 11:08:23.736263 Delta from base_000000010000000000000065_D_000000010000000000000064 at LSN 65000028
INFO: 2019/12/18 11:08:24.510685 Delta from base_000000010000000000000064_D_000000010000000000000062 at LSN 64000028
INFO: 2019/12/18 11:08:25.277768 Delta from base_000000010000000000000062 at LSN 62000028
INFO: 2019/12/18 11:08:26.680230 Finished extraction of part_003.tar.br
INFO: 2019/12/18 11:08:26.681372 Finished decompression of part_003.tar.br
INFO: 2019/12/18 11:11:33.948964 Finished decompression of part_001.tar.br
INFO: 2019/12/18 11:11:33.949970 Finished extraction of part_001.tar.br
INFO: 2019/12/18 11:11:34.073796 Finished extraction of pg_control.tar.br
INFO: 2019/12/18 11:11:34.080335
Backup extraction complete.
INFO: 2019/12/18 11:11:34.074887 Finished decompression of pg_control.tar.br
INFO: 2019/12/18 11:11:34.086287 base_000000010000000000000062 fetched. Upgrading from LSN 62000028 to LSN 64000028
INFO: 2019/12/18 11:11:34.432364 Finished extraction of part_001.tar.br
INFO: 2019/12/18 11:11:34.433393 Finished decompression of part_001.tar.br
INFO: 2019/12/18 11:11:34.532640 Finished extraction of part_003.tar.br
INFO: 2019/12/18 11:11:34.533689 Finished decompression of part_003.tar.br
INFO: 2019/12/18 11:11:34.627520 Finished extraction of pg_control.tar.br
INFO: 2019/12/18 11:11:34.628875
Backup extraction complete.
INFO: 2019/12/18 11:11:34.628510 Finished decompression of pg_control.tar.br
INFO: 2019/12/18 11:11:34.631066 base_000000010000000000000064_D_000000010000000000000062 fetched. Upgrading from LSN 64000028 to LSN 65000028
INFO: 2019/12/18 11:11:35.477902 Finished extraction of part_001.tar.br
INFO: 2019/12/18 11:11:35.479044 Finished decompression of part_001.tar.br
INFO: 2019/12/18 11:11:35.594967 Finished extraction of part_003.tar.br
INFO: 2019/12/18 11:11:35.596629 Finished decompression of part_003.tar.br
INFO: 2019/12/18 11:11:35.816534 Finished extraction of pg_control.tar.br
INFO: 2019/12/18 11:11:35.821772
Backup extraction complete.
INFO: 2019/12/18 11:11:35.818616 Finished decompression of pg_control.tar.br
INFO: 2019/12/18 11:11:35.833506 base_000000010000000000000065_D_000000010000000000000064 fetched. Upgrading from LSN 65000028 to LSN 67000028
INFO: 2019/12/18 11:11:36.204758 Finished extraction of part_001.tar.br
INFO: 2019/12/18 11:11:36.205871 Finished decompression of part_001.tar.br
INFO: 2019/12/18 11:11:36.218136 Finished extraction of part_003.tar.br
INFO: 2019/12/18 11:11:36.218145 Finished decompression of part_003.tar.br
INFO: 2019/12/18 11:11:36.334327 Finished extraction of pg_control.tar.br
INFO: 2019/12/18 11:11:36.335691
Backup extraction complete.
INFO: 2019/12/18 11:11:36.335671 Finished decompression of pg_control.tar.br
INFO: 2019/12/18 11:11:36.338122 base_000000010000000000000067_D_000000010000000000000065 fetched. Upgrading from LSN 67000028 to LSN 68000028
INFO: 2019/12/18 11:11:36.719773 Finished extraction of part_003.tar.br
INFO: 2019/12/18 11:11:36.720819 Finished decompression of part_003.tar.br
INFO: 2019/12/18 11:11:36.752751 Finished extraction of part_001.tar.br
INFO: 2019/12/18 11:11:36.754290 Finished decompression of part_001.tar.br
INFO: 2019/12/18 11:11:36.845509 Finished extraction of pg_control.tar.br
INFO: 2019/12/18 11:11:36.848143
Backup extraction complete.
INFO: 2019/12/18 11:11:36.846603 Finished decompression of pg_control.tar.br
INFO: 2019/12/18 11:11:36.851848 base_000000010000000000000068_D_000000010000000000000067 fetched. Upgrading from LSN 68000028 to LSN 69000028
INFO: 2019/12/18 11:11:37.221577 Finished extraction of part_001.tar.br
INFO: 2019/12/18 11:11:37.222881 Finished decompression of part_001.tar.br
INFO: 2019/12/18 11:11:37.257029 Finished extraction of part_003.tar.br
INFO: 2019/12/18 11:11:37.258142 Finished decompression of part_003.tar.br
INFO: 2019/12/18 11:11:37.401490 Finished extraction of pg_control.tar.br
INFO: 2019/12/18 11:11:37.403494
Backup extraction complete.
INFO: 2019/12/18 11:11:37.402758 Finished decompression of pg_control.tar.br
INFO: 2019/12/18 11:11:37.408147 base_000000010000000000000069_D_000000010000000000000068 fetched. Upgrading from LSN 69000028 to LSN 6b000028
INFO: 2019/12/18 11:11:37.710722 Finished decompression of part_003.tar.br
INFO: 2019/12/18 11:11:37.711774 Finished extraction of part_003.tar.br
INFO: 2019/12/18 11:11:37.717146 Finished decompression of part_001.tar.br
INFO: 2019/12/18 11:11:37.718182 Finished extraction of part_001.tar.br
INFO: 2019/12/18 11:11:37.801869 Finished decompression of pg_control.tar.br
INFO: 2019/12/18 11:11:37.802987 Finished extraction of pg_control.tar.br
INFO: 2019/12/18 11:11:37.804067
Backup extraction complete.
```

### CODE REVIEW

**Comment by tatodorov** [comment]
> 
> 
> > filepath.Join(basePrefix, location.Symlink)
> 
> Let's put it in a variable.

Already done.
The variable name is "symlinkName".

**Comment by tatodorov** [comment]
> 
> 
> What if it is not a symlink? Should we just return an error? Probably yes, but let's provide a more informative message about what exactly happened.

It must be a symlink.
When we create a tablespace, PostgreSQL will create a symlink with with name OID of the tablespace pointing to the location.

For instance:

**1. Create a new tablespace**
postgres=# CREATE TABLESPACE myts_loc LOCATION '/var/lib/postgresql/ts/myts_loc';
CREATE TABLESPACE

**2. Get the OID of the tablespace**
postgres=# SELECT spcname,oid FROM pg_tablespace WHERE spcname = 'myts_loc';
 spcname  |  oid
----------+-------
 myts_loc | 16385
(1 row)

**3. Go to $PGDATA/pg_tblspc**
postgres@bc0974acd020:~/10/main/pg_tblspc$ pwd
/var/lib/postgresql/10/main/pg_tblspc

**4. Get the location to which is pointing symbolic link 16385**
postgres@bc0974acd020:~/10/main/pg_tblspc$ ls -l 16385
lrwxrwxrwx 1 postgres postgres 31 Dec 23 20:43 16385 -> /var/lib/postgresql/ts/myts_loc

**Comment by tatodorov** [comment]
> 
> 
> Is it really a good idea to remove files which were probably not created by postgres or wal-g?
> I think, we should just return an error and let user clear it.
> 
> Or do you think it is possible when restoring from full backup that we need to change symlink targets?

Originally I considered the following scenario:
1. wal-g creates a full backup
2. Someone changes the location of a tablespace
So, from that point the symbolic link points to a new location that the one before creating a full backup.
3. wal-g creates a delta backup

When restoring the full backup the symbolic link will point to one location and when restoring from delta to another.

However, changing the location of tablespace is a work done outside of PostgreSQL (when the DB is shutdown move the data to a new location and update the symbolic link accordingly).
So, indeed it might be safer to just throw an error instead of trying to remove/create the symbolic link.
Already done.
If the current symbolic link does not point to the expected location, we will return an error.

**Comment by Van10000** [comment]
> > What if it is not a symlink? Should we just return an error? Probably yes, but let's provide a more informative message about what exactly happened.
> 
> It must be a symlink.
> When we create a tablespace, PostgreSQL will create a symlink with name OID of the tablespace pointing to the location.
> 
> For instance:
> 
> **1. Create a new tablespace**
> postgres=# CREATE TABLESPACE myts_loc LOCATION '/var/lib/postgresql/ts/myts_loc';
> CREATE TABLESPACE
> 
> **2. Get the OID of the tablespace**
> postgres=# SELECT spcname,oid FROM pg_tablespace WHERE spcname = 'myts_loc';
> spcname | oid
> ----------+-------
> myts_loc | 16385
> (1 row)
> 
> **3. Go to $PGDATA/pg_tblspc**
> postgres@bc0974acd020:~/10/main/pg_tblspc$ pwd
> /var/lib/postgresql/10/main/pg_tblspc
> 
> **4. Get the location to which is pointing symbolic link 16385**
> postgres@bc0974acd020:~/10/main/pg_tblspc$ ls -l 16385
> lrwxrwxrwx 1 postgres postgres 31 Dec 23 20:43 16385 -> /var/lib/postgresql/ts/myts_loc

Well, technically it doesn't have to be a symlink. Somebody might just put any file there. I don't know why would anybody do that, though.
Or worse, we could have a bug in backup creation and expect a symlink in a place where there is something else.
I think it's better to check that it's a symlink. And if not - write some informative message. Just in case.

**Comment by Van10000** [comment]
The rest of the code seems good to me.
Are you planning to write an integration test?

**Comment by tatodorov** [comment]
> 
> 
> > > What if it is not a symlink? Should we just return an error? Probably yes, but let's provide a more informative message about what exactly happened.
> > 
> > 
> > It must be a symlink.
> > When we create a tablespace, PostgreSQL will create a symlink with name OID of the tablespace pointing to the location.
> > For instance:
> > **1. Create a new tablespace**
> > postgres=# CREATE TABLESPACE myts_loc LOCATION '/var/lib/postgresql/ts/myts_loc';
> > CREATE TABLESPACE
> > **2. Get the OID of the tablespace**
> > postgres=# SELECT spcname,oid FROM pg_tablespace WHERE spcname = 'myts_loc';
> > spcname | oid
> > ----------+-------
> > myts_loc | 16385
> > (1 row)
> > **3. Go to $PGDATA/pg_tblspc**
> > postgres@bc0974acd020:~/10/main/pg_tblspc$ pwd
> > /var/lib/postgresql/10/main/pg_tblspc
> > **4. Get the location to which is pointing symbolic link 16385**
> > postgres@bc0974acd020:~/10/main/pg_tblspc$ ls -l 16385
> > lrwxrwxrwx 1 postgres postgres 31 Dec 23 20:43 16385 -> /var/lib/postgresql/ts/myts_loc
> 
> Well, technically it doesn't have to be a symlink. Somebody might just put any file there. I don't know why would anybody do that, though.
> Or worse, we could have a bug in backup creation and expect a symlink in a place where there is something else.
> I think it's better to check that it's a symlink. And if not - write some informative message. Just in case.

I added verification whether the target is a symlink and will throw an error if it is not.

**Comment by tatodorov** [comment]
> 
> 
> The rest of the code seems good to me.
> Are you planning to write an integration test?

I would like to create unit test, but facing the following challenges:
The code I am supposed to test in backup.go is in package "internal", but the test functions in backup_test.go are in package "internal_test".
I can specify the function to test by "internal.<FUNCTION>".
The problem is function "setTablespacePaths" is not exported and I cannot access it from another package.
I can export it, but that will require refactoring.
Also, in order to initialize a variable of type TablespaceSpec, I will need other functions from the "internal" package some of which are also not exported ("addTablespace" for instance).

Do you have any idea how to do it without too much refactoring?

If there are too many changes, I believe it would be better to have a separate PR only for adding the test.

**Comment by g0djan** [comment]
Hi, actually you can move backup_test.go to the internal package because we want to update our testing rules that test should be in the same package with code.

**Comment by tatodorov** [comment]
> 
> 
> Hi, actually you can move backup_test.go to the internal package because we want to update our testing rules that test should be in the same package with code.

Great, but I would prefer to do it in another PR.
This PR is for fixing the restore from delta backup, and in my opinion it would be better not to change anything in the code not related to that fix.

**Comment by thedevelopnik** [comment]
Just want to say thanks for working on this @tatodorov. I got blocked by this issue this week and was relieved to see an already open and active PR.

**Pull request closed without merging**
