### PR TITLE
Use io.CopyBuffer instead of custom realization in FastCopy

### PR DESCRIPTION
**Pull request by defntvdm**
so far only for tests #770

### CODE REVIEW

**Comment by x4m** [comment]
Maybe let's merge this?

**Comment by defntvdm** [comment]
Yes, we can. What editorialization you would like me to do?

**Comment by x4m** [comment]
What if we remove FastCopy() entirely? will it be faster?

**Comment by defntvdm** [comment]
I'm not sure. Every io.Copy allocate 32kb buffer. Maybe we want to prevent this behavior and use our Pool of buffers.

**Review by x4m — APPROVED** [review]
Yeah, it’s buffered, not fast. But fast is ok too, probably.

**Pull request merged**
