### PR TITLE
WIP - fix pg 15 remote backup

### PR DESCRIPTION
**Pull request by LeGEC**
### Database name

postgresql

# Pull request description

several things changed with postgresql 15 and replication connections

see #1385

### Describe what this PR fix

at the moment : running `wal-g backup-push` in remote mode triggers a Syntax error in postgresql

updating the package `github.com/jackc/pglogrepl` fixes that first issue.

At the moment, another error ("invalid tar header") is triggered at a later step.

### CODE REVIEW

**Review by serprex — CHANGES_REQUESTED** [review]
Remove WriteBackupListDetails test commit

**Comment by LeGEC** [comment]
as mentioned in https://github.com/wal-g/wal-g/issues/1385#issuecomment-1341454625 : there still is a bug with the current PR

When trying to write the backup files, the following error is triggered afterwards :

```
CompressAndEncrypt: compress: archive/tar: invalid tar header
```

The location where this error is returned is here :

https://github.com/wal-g/wal-g/blob/5b98d7142f153a9723c57a9f326cc77b87aeda13/pkg/storages/fs/folder.go#L115-L122

I haven't firgured out yet how the reader of that `io.Copy` is created, and what it tries to read.

**Comment by fatmaAliGamal** [comment]
wal-g backup-push when i use sudo -u postgres  wal-g backup-push {{ postgresql_data_dir }} running correct

**Comment by LeGEC** [comment]
unfortunately I don't have time to look into the 'tar' part of the issue.

I will close this pull request.

If the part about upgrading `pglogrepl` and `pgx` module is relevant, you are more than welcome to cherry pick the first commit (or to update theses two modules)

**Pull request closed without merging**
