### PR TITLE
Fix data race in uploader tests

### PR DESCRIPTION
**Pull request by usernamedt**
Fix data race introduced in https://github.com/wal-g/wal-g/pull/1423. For some reason, there were no CI tests triggered.

### CODE REVIEW

**Comment by serprex** [comment]
Why not revert #1423 until this is fixed?

**Comment by usernamedt** [comment]
> Why not revert #1423 until this is fixed?

I thought it would be an easy fix... :) But I guess you are right. I'll create a PR shortly.

**Comment by usernamedt** [comment]
> Why not revert #1423 until this is fixed?

https://github.com/wal-g/wal-g/pull/1442

**Comment by usernamedt** [comment]
I'll reopen it with the correct branch.

**Pull request closed without merging**
