### PR TITLE
AZURE_STORAGE_SAS_TOKEN support

### PR DESCRIPTION
**Pull request by serprex**
Exposes https://github.com/wal-g/storages/pull/18

### CODE REVIEW

**Comment by x4m** [comment]
Cool, thanks! Do we need to bump ```storages```? Or is it bumped already?

BTW, it seems that CI is broken, but it's not caused by this PR..

**Comment by serprex** [comment]
Yes, likely need to bump versions, I was testing with using `replace` in `go.mod` to use my local copy

**Comment by byucesoy** [comment]
Hi @x4m, @serprex, I'm writing to bumping up this PR. Are there any plans to proceed with this?

**Comment by x4m** [comment]
Sorry for the delay
finally CI passed
LGTM

**Comment by byucesoy** [comment]
Thanks a lot @serprex for the PR and @x4m for the review and merge.

**Pull request merged**
