### PR TITLE
Azure: Add SA endpoints for non AzurePublicCloud

### PR DESCRIPTION
**Pull request by theok-nice**
Addresses issue : [#856](https://github.com/wal-g/wal-g/issues/856)

Changes allow wal-g to work in regions other than AzurePublicCloud.
It adds optional config setting where user can select AzureUSGovernmentCloud, AzureChinaCloud, AzureGermanCloud.
When one of these three options is selected, module will select correct storage account endpoint. For the correct endpoint I am using https://pkg.go.dev/github.com/Azure/go-autorest/autorest/azure module.

If setting is missing from the wal-g config file,or set to any other value (including "AzurePublicCloud") will default to AzurePublicCloud's endpoint.

### CODE REVIEW

**Comment by theok-nice** [comment]
I don't understand why these tests fail on code that I haven't change in my commit. Not sure how to resolve this.

**Review by x4m — APPROVED** [review]
Thanks!
WAL-G is now able to work with the government cloud. Sounds cool 😎

**Comment by x4m** [comment]
> I don't understand why these tests fail on code that I haven't change in my commit. Not sure how to resolve this.

We added few new checkers recently and still are working to fix all those problems found by these checkers.

**Comment by kim0** [comment]
Thanks @theok-nice .. One typo exists I think .. It says to use `AZURE_STORAGE_SAS_TOKEN`, while I guess the correct one should be `AZURE_ENVIRONMENT_NAME` right ?

**Pull request merged**
