### PR TITLE
Add rating tar ball composer

### PR DESCRIPTION
**Pull request by usernamedt**
RatingTarBallComposer receives all files and tar headers which are going to be written to the backup and composes the tarballs by placing the files with similar update rating in the same tarballs.

Also, there is a new StatBundleFiles implementation of BundleFiles which uses the statistics about page files updates count from pg_stat_all_tables and records this statistics into backup sentinel json. This information is used in future backups by ComposeRatingEvaluator to calculate the update rating for file.

### CODE REVIEW

**Comment by g0djan** [comment]
Check that wal-g with this flag works in tests.

**Comment by g0djan** [comment]
How about docker test?

**Comment by usernamedt** [comment]
> How about docker test?

Added docker test in https://github.com/wal-g/wal-g/pull/734/commits/e5fd8062dd846152ecf32f2ef1a8b21fc41765b8

**Review by g0djan — APPROVED** [review]
Rebase

**Pull request merged**
