### PR TITLE
Update LazyCache to be generic

### PR DESCRIPTION
**Pull request by serprex**
Add Key/Value type parameters

Increases minimum go version to 1.18

### CODE REVIEW

**Comment by ldez** [comment]
Hello,

you have to add the following lines in your configuration:
```yml
run:
    go: 1.18
```

**Comment by ldez** [comment]
You don't have to disable gocritic, you can just disable the rule `hugeParam`.

https://github.com/golangci/golangci-lint/pull/2438

**Comment by ldez** [comment]
You just removed the configuration instead of the rule.

**Comment by serprex** [comment]
@ldez trying to search how to disable rule

**Comment by ldez** [comment]
I will help you

**Comment by ldez** [comment]
You can use this file:
```yml
# This file contains all available configuration options
# with their default values.

# all available settings of specific linters
linters-settings:
  modules-download-mode: vendor
  dupl:
    threshold: 400
  funlen:
    lines: 100
    statements: 50
  gocritic:
    enabled-tags:
      - performance
    disabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy
    # settings:
    #   hugeParam:
    #     sizeThreshold: 170 # temporary, default is 80
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: false
  misspell:
    locale: US
  lll:
    line-length: 140

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - funlen
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - nakedret
    - exportloopref
    - staticcheck
    # - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    # - revive
    - lll
    - deadcode
    - stylecheck
    - gosimple
    - whitespace

run:
  go: 1.18
  timeout: 5m
  skip-dirs:
    - "cmd/redis"
    - "internal/databases/redis"
    - "tests_func"
    - "tmp"
    - "submodules"
    - "testtools"
    - "pkg/storages"
  skip-files:
    - ".*_test.go$"

severity:
  default-severity: error
  rules:
    - linters:
        - godox
        - deadcode
      severity: info
```

**Comment by ldez** [comment]
for `revive` and `structcheck`, I think that you can apply the suggestions made by these linters:
```
internal/walparser/read_xlog_record.go:178:37: var-declaration: should drop = nil from declaration of var lastRelFileNode; it is the zero value (revive)
        var lastRelFileNode *RelFileNode = nil
                                           ^
internal/extract.go:161:25: error-strings: error strings should not be capitalized or end with punctuation or a newline (revive)
                        return errors.Errorf("failed to extract files:\n%s\n",
                                             ^
internal/fetch_helper.go:24:48: error-strings: error strings should not be capitalized or end with punctuation or a newline (revive)
        return ArchiveNonExistenceError{errors.Errorf("Archive '%s' does not exist.\n", archiveName)}
                                                      ^
internal/backup_mark.go:186:17: error-strings: error strings should not be capitalized or end with punctuation or a newline (revive)
                errors.Errorf("Can't mark backup '%s' as impermanent. There is permanent increment backup.",
                              ^
internal/databases/mysql/mysql_binlog.go:122:18: var-declaration: should drop = 0 from declaration of var ts; it is the zero value (revive)
        var ts uint32 = 0
                        ^
internal/databases/postgres/copy_tar_ball_composer.go:238:33: var-declaration: should drop = nil from declaration of var tarBall; it is the zero value (revive)
        var tarBall internal.TarBall = nil
                                       ^
internal/databases/postgres/bguploader.go:175:26: var-declaration: should drop = 0 from declaration of var numUploaded; it is the zero value (revive)
        var numUploaded int32 = 0
                                ^
internal/databases/postgres/backup.go:22:33: var-declaration: should drop = nil from declaration of var UnwrapAll; it is the zero value (revive)
var UnwrapAll map[string]bool = nil
                                ^
internal/databases/postgres/configure.go:43:43: var-declaration: should drop = nil from declaration of var deltaFileManager; it is the zero value (revive)
        var deltaFileManager *DeltaFileManager = nil
                                                 ^
internal/lazy_cache.go:24:2: `cache` is unused (structcheck)
        cache      map[K]V
        ^
internal/lazy_cache.go:25:2: `load` is unused (structcheck)
        load       func(key K) (value V, err error)
        ^
internal/lazy_cache.go:26:2: `cacheMutex` is unused (structcheck)
        cacheMutex sync.Mutex
        ^
```

**Comment by ldez** [comment]
But for `structcheck`, it's false-negative related to generics.

**Comment by serprex** [comment]
Thanks. I'll be putting `revive` / `error-strings` fixes in a separate PR

**Review by usernamedt — APPROVED** [review]
LGTM

**Pull request merged**
