### PR TITLE
Avoid GetBucketLocation api call for Minio

### PR DESCRIPTION
**Pull request by tamalsaha**
Fixes https://github.com/kubedb/project/issues/209

### CODE REVIEW

**Comment by tamalsaha** [comment]
cc: @the-redback @hossainemruz

**Comment by x4m** [comment]
Looks good, thanks!
Can you add some tests?

**Comment by tamalsaha** [comment]
@x4m, added tests. PTAL

**Comment by x4m** [comment]
Thanks, pushed

**Pull request merged**
