### PR TITLE
release: unify amd64 <--> arm64 names

### LINKED ISSUE #1853: Unified binary names
### Database name
PostgreSQL

# Issue description

The published binaries for AMD64 and ARM64 have different format of filenames. For example, `wal-g-pg-ubuntu20.04-aarch64` has no dash after "ubuntu" while `wal-g-pg-ubuntu-20.04-amd64` does.

### Describe your problem
This difference is a bit inconvenient when I use Ansible to install wal-g binaries to hosts with multiple architectures. My suggestion is that only the arch indicator should change and no other part of the filename, it could be helpful if I could use only `{{ ansible_architecture }}` to select between binaries.

### PR DESCRIPTION
**Pull request by chipitsine**
fixes #1853

### CODE REVIEW

**Comment by chipitsine** [comment]
@stl-victor-sudakov fyi

**Comment by stl-victor-sudakov** [comment]
Wow, great, thanks!

**Comment by chipitsine** [comment]
Ping

**Comment by stl-victor-sudakov** [comment]
Pong

**Comment by x4m** [comment]
let's merge?

**Comment by chipitsine** [comment]
> let's merge?
> 

Yes

**Review by x4m — APPROVED** [review]

**Pull request merged**
