### PR TITLE
make mongo docker compose tests more stable

### PR DESCRIPTION
**Pull request by chipitsine**
### Describe what this PR fix

ci mongodb tests fail from time to time

### CODE REVIEW

**Comment by x4m** [comment]
@VGoshev can you please take a look?

**Comment by chipitsine** [comment]
if nobody minds, I'll merge it.
it makes tests more robust at least partially

**Comment by chipitsine** [comment]
@VGoshev , gently ping

**Comment by chipitsine** [comment]
Ping, ping

**Comment by chipitsine** [comment]
ping, ping, ping

**Review by x4m — APPROVED** [review]

**Pull request merged**
