### PR TITLE
upload: abort if WALE_S3_PREFIX doesn't look like a url

### PR DESCRIPTION
**Pull request by adamdecaf**

### CODE REVIEW

**Comment by x4m** [comment]
Hi! Thanks for the pull request!
Are you sure this is the only protocol acceptable by Go SDK AWS? If so, surely your code is correct. What is the best way to check that?

**Comment by adamdecaf** [comment]
> Are you sure this is the only protocol acceptable by Go SDK AWS?

I'm not sure about that.. It looks like minio cares more about the endpoint url being changed. How about we error if the Scheme || Host are empty strings? Both are required anyway. 

https://docs.minio.io/docs/aws-cli-with-minio
https://docs.minio.io/docs/golang-client-quickstart-guide
https://open.microsoft.com/2017/11/09/s3cmd-amazon-s3-compatible-apps-azure-storage/

**Comment by x4m** [comment]
Sounds reasonable.
I've seen installations working with https+s3, but this prefix was not working for WAL-G.

**Comment by adamdecaf** [comment]
Updated.

**Comment by x4m** [comment]
Thanks, pushed.

**Pull request merged**
