### PR TITLE
Remove leftover references to WAL-E

### PR DESCRIPTION
**Pull request by davidfetter**
This is a separate project now. It should have its own names.

### CODE REVIEW

**Comment by x4m** [comment]
Thanks, David!

I like the idea. But I have two concerns:
1. This will break existing installations
2. WAL-G is designed to be an easy replacement for WAL-E
3. For example, TestDecryptWALElzo -> TestDecryptWALGlzo is conceptually incorrect, WAL-G does not use Lzo for it's files, Lzo support is here for backward compatibility. You can switch to WAL-G from running WAL-E cluster by configuring your replicas first. WAL-G can wal-fetch files of WAL-E.

**Comment by x4m** [comment]
I'm boarding on a plane right now, will respond on other your items after arrival. Many thanks for your work!

**Comment by davidfetter** [comment]
How about a backward-compatibility mode?

**Comment by x4m** [comment]
I think that it is a good idea to have all "WALE_*" settings backed by corresponding "WALG_*" settings, and then leave small note that WALE settings are supported too, removing them from the main docs section. Sorry for answering so long.

**Comment by x4m** [comment]
@davidfetter may I ask you to look into https://github.com/x4m/wal-g/commit/4eaf7f65da42af8f88372009a4e3d81292c96487 ?
How do you think, is it what we want here? Can we make it better?

**Comment by x4m** [comment]
Thanks! This work was partially merged in #111

**Pull request closed without merging**
